openapi: '3.0.2'
info:
  title: API Tickets & sales
  version: '0.1'
servers:
  - url: https://9shjd4c13a.execute-api.sa-east-1.amazonaws.com/dev/

paths:
  /tickets:
    post:
      summary: Create a ticket
      tags: 
        - Tickets
      security:
        BearerAuth: []
      requestBody:
        description: Data for create a ticket
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
      responses:
        '201':
          description: Ticket created correctly
        '400':
          description: Ticket could not be created
        '401':
          description: Unauthorized email or token
    get:
      summary: Get all tickets
      tags:
        - Tickets
      security:
        BearerAuth: []
      responses:
        '200':
          description: List of all tickets
        '401':
          description: Unauthorized email or token
  /tickets/{id}:
    get:
      summary: Get a ticket by id
      tags:
        - Tickets
      security:
        BearerAuth: []
      parameters:
        - in: path
          name: ticketID
          schema: 
            type: string
            format: uuid
      responses:
        '200':
          description: Get the requested ticket
        '401':
          description: Unauthorized email or token
        '403':
          description: Forbidden
        '404':
          description: Ticket not found
    put:
      summary: Update a ticket
      tags:
        - Tickets
      security:
        BearerAuth: []
      parameters:
        - in: path
          name: ticketId
          schema:
            type: string
            format: uuid
      
      responses: 
        '200':
          description: Ticket updated
        '400':
          description: Bad request
        '401':
          description: Unauthorized email or token
        '403':
          description: Forbidden
        '404':
          description: Not Found

    delete:
      summary: Delete a ticket
      tags:
        - Tickets
      security:
        BearerAuth: []
      parameters:
        - in: path
          name: ticketId
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Ticket deleted
        '401':
          description: Unauthorized email or token
        '403':
          description: Forbidden
        '404':
          description: Ticket not found
  /sales:
    get:
      summary: Get a list of sales
      tags:
        - Sales
      security:
        BearerAuth: []
        
      responses:
        '200':
          description: List of sales
        '401': 
          description: Unauthorized email or token
  /sales/{id}:
    get:
      summary: Get a sale by id
      tags:
        - Sales
      security:
        BearerAuth: []
      parameters:
        - in: path
          name: saleId
          schema:
            type: string
            format: uuid

components:
  schemas:
    Ticket:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        publicationDate:
          type: string
          format: date-time
        status:
          type: integer
      
  securitySchemes: 
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT